---
title: 'Home Page'
---

{% extends 'src/layouts/wwwBase.swig' %}
{% block content %}
<div id="marketing-content">
<section id="hero">
	<h1>Golf with Friends</h1>
	<div class="overlay"></div>
	<nav>
		<a href="/app">Go to app <i class="fa fa-arrow-right"></i></a>
	</nav>
</section>
<section id="hero2"></section>
<section id="hero3"></section>
</div>
<footer>

</footer>

{% endblock %}


{% block scripts %}
{% endblock %}
